version: "2"

# sets database data to local
volumes:
  db-data:
    external: false
  redis: 
  node_module:
services: 
  db:
    image: postgres:12
    volumes:
      - db-data:/usr/local/pgsql/data
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:

  redis:
    image: redis:5.0.5
    command: redis-server
    volumes:
      - 'redis:/usr/local/redis/data'
  
  sidekiq:
    depends_on:
      - 'db'
      - 'redis'
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - '.:/usr/src/app'
    env_file: '.env'
  
  frontend: 
    build: ./frontend
    command: npm start
    volumes:
      - ./frontend/:/usr/src/app
      - node_module:/usr/src/app/node_modules # What this is, when dockerfile npm installs, a node_module folder is created, but needs to be accessed via volumes.
    ports:
      - "3000:3000"
      - "35729:35729"
    env_file: '.env'

  app:
    depends_on:
      - 'db'
      - 'redis'
    build: .
    volumes:
      - .:/usr/src/app
    ports: 
      - "3001:3001"
    stdin_open: true
    tty: true
    env_file: '.env'



  