default: &default
  adapter: postgresql
  host: <%= ENV["POSTGRES_HOST"] %>
  username: <%= ENV["POSTGRES_USER"] %>
  encoding: unicode
  pool: 2
  timeout: 5000
  
development:
  <<: *default
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  database: urlshortener_development


test:
  <<: *default
  database: urlshortener_test
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  database: urlshortener_production
  url: <%= ENV['DATABASE_URL'] %>
  password: <%= ENV['URLSHORTENER_DATABASE_PASSWORD'] %>